name: Backend CI

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  workflow_dispatch: {}

defaults: { run: { working-directory: backend } }

jobs:
  fmt:
    name: Rust formatting (nightly)
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with: { components: rustfmt }
      - uses: Swatinem/rust-cache@v2
        with: { workspaces: backend }
      - run: cargo fmt --check

  lint:
    name: Rust linting
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.91.0
        with: { components: clippy }
      - uses: Swatinem/rust-cache@v2
        with: { workspaces: backend }
      - run: cargo clippy

  test:
    name: Rust tests
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.91.0
      - uses: Swatinem/rust-cache@v2
        with: { workspaces: backend }
      - run: cargo test
