name: CI

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch: {}

jobs:
  format:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with: { components: rustfmt }
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check

  lint:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.91.0
        with: { components: clippy }
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy

  test:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.91.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo test
